### ISSUE TITLE
Need a branch and docker tag for stable jobs

### ISSUE THREAD

**Issue by tobias-urdin** [gnocchixyz/ci-tools#34]
We need to create a stable/4.3 branch for this repo from commit 7adc98b45a56012ea36f61fbcc3d9325e7ea4513

Then make sure we build a stable-4.3 tag in DockerHub so that we can use on the stable/4.3 branch for testing since we
still need python2 support there.

**Comment by tobias-urdin** [comment]
@jd dont have access to create a branch or fix dockerhub, can you help?

**Comment by chungg** [comment]
created a stable/4.3 branch

**Comment by jd** [comment]
don't forget to the set the right docker image tag I guess

**Comment by tobias-urdin** [comment]
did any of you setup an automated build in dockerhub for this new branch?

**Comment by chungg** [comment]
:/ i'm not entirely sure who has access to that account.

**Comment by tobias-urdin** [comment]
maybe @jd has?

**Comment by jd** [comment]
If you have docker hub username, I can add you guys.

**Comment by jd** [comment]
![Uploading Screenshot 2020-10-01 at 23.56.32.png…]()

**Comment by jd** [comment]
![Screenshot 2020-10-01 at 23 56 32](https://user-images.githubusercontent.com/2644/94867577-c9cd6a80-0441-11eb-8123-17cdcdec2c77.png)

**Comment by jd** [comment]
Ok I reconfigured it because the Dockerfile is not at the root…
![Screenshot 2020-10-02 at 00 01 39](https://user-images.githubusercontent.com/2644/94867948-7c053200-0442-11eb-8d06-e46234a824a0.png)

**Comment by tobias-urdin** [comment]
you can add tobiasurdin @jd i assume you need to specify the name and path to the travis-ci-image.dockerfile file

**Comment by jd** [comment]
It might need a git push to `stable/4.3` to be retriggered.

**Comment by jd** [comment]
I've added you @tobias-urdin
